# https://docs.docker.com/compose/compose-file/05-services/#image
services:
  php:
    image: ghcr.io/sebsept/docker-php-symfony-starter:prod
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: tmpfs
        target: /app/var
    user: "0:1000"
    networks:
      - nginx
      - postgres
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    # service name is the hostname
    image: postgres:16.1
    env_file:
      - .env.local
    expose:
      - 5432
    volumes:
      - type: volume
        source: postgres_data_prod
        target: /var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - postgres

  nginx:
    image: nginx:1.21.3
    ports:
      - target: 80
        published: 80
    volumes:
      # nginx config
      - type: bind
        source: ./configs/nginx_default.conf
        target: /etc/nginx/conf.d/default.conf
      # assets
      - type: bind
        source: ./public
        target: /app/public
    depends_on:
      - php
    restart: unless-stopped
    networks:
      - nginx

volumes:
  postgres_data_prod:

networks:
  nginx:
  postgres:
  php:
