# https://docs.docker.com/compose/compose-file/05-services/#image
services:
  php:
    image: ghcr.io/sebsept/docker-php-symfony-starter:dev
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: tmpfs
        target: /app/var
    user: "0:1000"
    networks:
      - nginx
      - postgres
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    # @todo : utiliser un fichier de config pour la version de postgres
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soignemoi
    expose:
      - 5432
    # ports : pour debogage - ne pas  utiliser en prod @todo
    ports:
      - target: 5432
        published: 32770
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - postgres

  nginx:
    # https://hub.docker.com/r/library/nginx/tags
    image: nginx:1.26.0
    ports:
      - target: 80
        published: 32772
    volumes:
      # nginx config
      - type: bind
        source: ./docker/nginx_dev.conf
        target: /etc/nginx/conf.d/default.conf
      # assets
      - type: bind
        source: ./public
        target: /app/public
    depends_on:
      - php
    restart: unless-stopped
    networks:
      - nginx
      - partage

volumes:
  postgres_data:

networks:
  nginx:
  postgres:
  php:
  partage:
    external: true