<?php

namespace App\DataFixtures;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class PrescriptionItemFixtures extends Fixture
{
    public function load(ObjectManager $objectManager): void
    {
        // PrescriptionItems are generated by the PrescriptionFixtures class
    }
}
