name: Composer check & CI

on:
  workflow_call:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: docker compose
        run: |
          set -e
          docker network create partage
          docker compose --progress quiet -f compose-dev.yaml up -d --build
          docker compose -f compose-dev.yaml exec php composer install --quiet

      - name: check composer vulnerabilities
        run: docker compose -f compose-dev.yaml exec -it php /app/check_composer.sh

      - name: run composer ci script
        run: docker compose -f compose-dev.yaml exec php composer run-script ci
