name: Deployment

on:
  push:
    branches:
      - main

jobs:
  integration:
    uses: ./.github/workflows/integration.yaml
    secrets: inherit
  deploy:
    needs: integration
    runs-on: ubuntu-latest

    steps:
      - name: Deployment
        uses: appleboy/ssh-action@f9163462563f649b27272d32e585525a5fe68d76
        with:
          host: api.ecf.seb7.fr
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            if [ ! -d "/app" ]; then
              git clone --depth=1 --branch main git@github.com:SebSept/soignemoi-api.git /app
            fi
            cd /app
            git fetch origin main --depth=1
            git reset --hard origin/main --
            docker compose -f compose-prod.yaml pull
            docker compose -f compose-prod.yaml down
            docker compose -f compose-prod.yaml up -d --build
            docker compose -f compose-prod.yaml exec -u root php composer install --no-dev --working-dir=/app
            docker compose -f compose-prod.yaml exec php ./bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
            docker compose -f compose-prod.yaml exec -u root php chown www-data:www-data /app/var /app/public 

      - name: Check API is running
        run: curl -s --fail https://api.ecf.seb7.fr