name: Deploy on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # pour le moment on ne lance pas tests et de verifs
      # @todo tests, lint, etc
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: api.ecf.seb7.fr
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: whoami
